[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"

[environments]
[environments.production]
variables = { 
  NODE_ENV = "production",
  PORT = "3000",
  HOSTNAME = "0.0.0.0"
}